app:
  description: Test modern compositor with pictex effects
  icon: "\U0001F3A8"
  icon_background: "#FF5722"
  mode: advanced-chat
  name: Test Compose Modern
  use_icon_as_answer_icon: false

kind: app
version: 0.1.3

workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      enabled: false
      image:
        enabled: false
    opening_statement: "Enter hook, body, and CTA text to generate a modern ad creative."
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
  graph:
    edges:
      - data:
          isInIteration: false
          sourceType: start
          targetType: http-request
        id: e1
        source: "1"
        sourceHandle: source
        target: "2"
        targetHandle: target
        type: custom
      - data:
          isInIteration: false
          sourceType: http-request
          targetType: code
        id: e2
        source: "2"
        sourceHandle: source
        target: "3"
        targetHandle: target
        type: custom
      - data:
          isInIteration: false
          sourceType: code
          targetType: answer
        id: e3
        source: "3"
        sourceHandle: source
        target: "4"
        targetHandle: target
        type: custom
    nodes:
      - data:
          desc: "Enter ad text"
          selected: false
          title: Start
          type: start
          variables:
            - label: "Hook Text"
              max_length: 500
              required: true
              type: text-input
              variable: hook_text
            - label: "Body Text"
              max_length: 500
              required: false
              type: text-input
              variable: body_text
            - label: "CTA Text"
              max_length: 100
              required: false
              type: text-input
              variable: cta_text
            - label: "Preset"
              required: false
              type: select
              variable: preset
              options:
                - "neon"
                - "minimal"
                - "gradient"
                - "bold"
                - "glass"
        height: 54
        id: "1"
        position:
          x: 30
          y: 300
        type: custom
        width: 244

      - data:
          authorization:
            config: null
            type: no-auth
          body:
            data: ""
            type: none
          desc: Call compose-modern API
          headers: ""
          method: post
          params: "hook_text:{{#1.hook_text#}}\nbody_text:{{#1.body_text#}}\ncta_text:{{#1.cta_text#}}\npreset:{{#1.preset#}}\noutput_size:instagram_square"
          timeout:
            connect: 60
            max_connect_timeout: 60
            max_read_timeout: 120
            max_write_timeout: 120
            read: 120
            write: 120
          title: Compose Modern
          type: http-request
          url: https://creo.yourads.io/tools/compose-modern
          variables: []
        height: 98
        id: "2"
        position:
          x: 334
          y: 300
        type: custom
        width: 244

      - data:
          code: |
            import json

            def main(body: str) -> dict:
                try:
                    data = json.loads(body)
                    if data.get("success"):
                        return {"url": data["url"]}
                    return {"url": "Error: " + data.get("error", "Unknown")}
                except Exception as e:
                    return {"url": "Error: " + str(e)}
          code_language: python3
          desc: Parse response
          outputs:
            url:
              type: string
          selected: false
          title: Parse Result
          type: code
          variables:
            - value_selector:
                - "2"
                - body
              variable: body
        height: 98
        id: "3"
        position:
          x: 638
          y: 300
        type: custom
        width: 244

      - data:
          answer: "**Your Ad:**\n{{#3.url#}}"
          desc: ""
          selected: false
          title: Answer
          type: answer
          variables: []
        height: 107
        id: "4"
        position:
          x: 942
          y: 300
        type: custom
        width: 244
    viewport:
      x: 0
      y: 0
      zoom: 0.5
